db:
    image: postgres
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
        - POSTGRES_ROOT_PASSWORD=root_password

keycloak:
    image: jboss/keycloak-postgres
    environment:
        - KEYCLOAK_LOGLEVEL=DEBUG
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=123456
    links:
        - db:postgres
    ports:
        - "8089:8080"
        - "9999:9990"
        - "443:8443"
    volumes:
        - ./data:/data